apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # This MUST use the dynamic values name to avoid 409 database locks
  name: {{ values.name }}-{{values.language | lower | replace " " "-" }}
  description: "Scaffolded application using the {{ values.language }} stack"
spec:
  type: service
  lifecycle: experimental
  owner: {{ values.owner }}
